# Generated by Django 4.1.4 on 2022-12-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="name",
            field=models.CharField(
                choices=[
                    ("SMS", "SMS"),
                    ("E-Mail", "E-Mail"),
                    ("Push Notification", "Push Notification"),
                ],
                default="SMS",
                max_length=25,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="messagecategories",
            name="name",
            field=models.CharField(
                choices=[
                    ("Sports", "Sports"),
                    ("Finance", "Finance"),
                    ("Movies", "Movies"),
                ],
                default="Sports",
                max_length=25,
                unique=True,
            ),
        ),
    ]
