# Generated by Django 4.1.4 on 2022-12-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_channel_name_alter_messagecategories_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
