# Generated by Django 4.1.4 on 2022-12-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_log_created_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagecategories',
            options={'verbose_name_plural': 'Message Categories'},
        ),
    ]
